[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm ci --production=false']

[phases.build]
cmds = ['cd backend && npx prisma generate && npm run build']

[start]
cmd = 'cd backend && node dist/server.js'
